DROP TABLE ORDER2;
DROP TABLE BASKET;
DROP TABLE ORDER1;
DROP TABLE ITEM;
DROP TABLE CUSTOMER;

CREATE TABLE CUSTOMER(
        CUSTOMER_ID VARCHAR2(100) PRIMARY KEY,
        CUSTOMER_NAME VARCHAR2(50) NOT NULL,
        CUSTOMER_ADD VARCHAR2(200) NOT NULL,
        CUSTOMER_TEL VARCHAR2(100) NOT NULL UNIQUE,
        CUSTOMER_EMAIL VARCHAR2(100) NOT NULL UNIQUE
);

CREATE TABLE ITEM(
        ITEM_CODE VARCHAR2(30) PRIMARY KEY,
        ITEM_NAME VARCHAR2(100) NOT NULL,
        ITEM_PRICE NUMBER(38) NOT NULL,
        ITEM_STOCK NUMBER(20) 
);

CREATE TABLE BASKET(
        CUSTOMER_ID VARCHAR2(100) REFERENCES CUSTOMER(CUSTOMER_ID),
        ITEM_CODE VARCHAR2(30) REFERENCES ITEM(ITEM_CODE),
        ITEM_QUANTITY NUMBER(10),
        TOTAL_PRICE NUMBER(20)
);
CREATE TABLE ORDER1 (
        ORDER_NUMBER NUMBER(30) PRIMARY KEY,
        CUSTOMER_ID VARCHAR2(100) REFERENCES CUSTOMER(CUSTOMER_ID),
        ORDER_DATE DATE  DEFAULT SYSDATE,
        ORDER_NAME VARCHAR2(50) ,
        ORDER_ADD VARCHAR2(200) ,
        ORDER_TEL VARCHAR2(100) 
);

CREATE SEQUENCE ORDER_SQ 
        START WITH 1
        INCREMENT BY 1
        MAXVALUE 9999
        MINVALUE 0
        NOCYCLE
        NOCACHE;
        
CREATE TABLE ORDER2(
        ORDER_NUMBER NUMBER(30) REFERENCES ORDER1(ORDER_NUMBER),
        ITEM_CODE VARCHAR2(30) REFERENCES ITEM(ITEM_CODE),
        ITEM_QUANTITY NUMBER(10) NOT NULL,
        TOTAL_PRICE NUMBER(20)
);

DESC CUSTOMER;
DESC ITEM;
DESC BASKET;
DESC ORDER1;
DESC ORDER2;