-- [ XI ] INDEX  : 조회속도를 빠르게 하기위함.
SELECT * FROM USER_INDEXES;     -- 딕셔너리뷰에 SCOTT이 소유한 인덱스 정보
DROP TABLE EMP01;
CREATE TABLE EMP01
        AS SELECT * FROM EMP;  
SELECT * FROM EMP01;
INSERT INTO EMP01 SELECT * FROM EMP01;
SELECT COUNT(*) FROM EMP01;
SELECT TO_CHAR(COUNT(*),'9,999,999') FROM EMP01;
INSERT INTO EMP01 (EMPNO, ENAME , DEPTNO) VALUES (1111,'홍',40);
INSERT INTO EMP01 SELECT * FROM EMP01;
DESC EMP01;
SELECT * FROM EMP01 WHERE ENAME = '홍';          -- 0.03초
-- 인덱스 생성후 빠른 조회
CREATE INDEX INDEX_EMP01_ENAME
ON EMP01(ENAME);
SELECT * FROM EMP01 WHERE ENAME= '홍';           -- 0.004초
SELECT * FROM USER_INDEXES;
-- DROP INDEX INDEX_EMP01_ENAME;
DROP TABLE EMP01;               -- INDEX도 같이 삭제
